/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appPublicChatIdIndexRouteImport } from './routes/(app)/public/$chatId/index'
import { Route as appPrivateChatIdIndexRouteImport } from './routes/(app)/private/$chatId/index'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appPublicChatIdIndexRoute = appPublicChatIdIndexRouteImport.update({
  id: '/public/$chatId/',
  path: '/public/$chatId/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPrivateChatIdIndexRoute = appPrivateChatIdIndexRouteImport.update({
  id: '/private/$chatId/',
  path: '/private/$chatId/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/private/$chatId': typeof appPrivateChatIdIndexRoute
  '/public/$chatId': typeof appPublicChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/private/$chatId': typeof appPrivateChatIdIndexRoute
  '/public/$chatId': typeof appPublicChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/private/$chatId/': typeof appPrivateChatIdIndexRoute
  '/(app)/public/$chatId/': typeof appPublicChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/private/$chatId'
    | '/public/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/private/$chatId' | '/public/$chatId'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(app)/'
    | '/(app)/private/$chatId/'
    | '/(app)/public/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/public/$chatId/': {
      id: '/(app)/public/$chatId/'
      path: '/public/$chatId'
      fullPath: '/public/$chatId'
      preLoaderRoute: typeof appPublicChatIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/private/$chatId/': {
      id: '/(app)/private/$chatId/'
      path: '/private/$chatId'
      fullPath: '/private/$chatId'
      preLoaderRoute: typeof appPrivateChatIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appPrivateChatIdIndexRoute: typeof appPrivateChatIdIndexRoute
  appPublicChatIdIndexRoute: typeof appPublicChatIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appPrivateChatIdIndexRoute: appPrivateChatIdIndexRoute,
  appPublicChatIdIndexRoute: appPublicChatIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
